# Generated by Django 4.2.5 on 2023-09-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='reg_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='reg_event',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='reg_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='reg_phone',
            new_name='phone',
        ),
    ]
